# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # #                                   ¡¡NO EDITAR!!                                       # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Componente del climatizador
external_components:
  - source:
      url: https://github.com/atiscornia/tclac.git
      type: git
      ref: master
    components: [ tclac ]
    refresh: 30s

# Configuración ESPHome
esphome:
  name: ${device_name}
  min_version: 2023.3.0
  friendly_name: ${humanly_name}
  on_boot:
    priority: -100
    then:
      lambda: !lambda |-
        id(${device_name}climate).set_beeper_state(false);
        id(${device_name}climate).set_force_mode_state(false);
        
        if (id(display_mode).state){
          id(${device_name}climate).set_display_state(true);
        } else {
          id(${device_name}climate).set_display_state(false);
        }
        if (id(ledflash_mode).state){
          id(${device_name}climate).set_module_display_state(true);
        } else {
          id(${device_name}climate).set_module_display_state(false);
        }
        
        if (id(vswing).active_index() == 0){
          id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UP_DOWN);
        } else if (id(vswing).active_index() == 1){
          id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UPSIDE);
        } else if (id(vswing).active_index() == 2){
          id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::DOWNSIDE);
        }
        
        if (id(vfixing).active_index() == 0){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::LAST);
        } else if (id(vfixing).active_index() == 1){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_UP);
        } else if (id(vfixing).active_index() == 2){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::UP);
        } else if (id(vfixing).active_index() == 3){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::CENTER);
        } else if (id(vfixing).active_index() == 4){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::DOWN);
        } else if (id(vfixing).active_index() == 5){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_DOWN);
        }
        
        if (id(beep_mode).state){
          id(${device_name}climate).set_beeper_state(true);
        } else {
          id(${device_name}climate).set_beeper_state(false);
        }
        if (id(force_mode).state){
          id(${device_name}climate).set_force_mode_state(true);
        } else {
          id(${device_name}climate).set_force_mode_state(false);
        }

uart:
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_pin: ${uart_rx}
  tx_pin: ${uart_tx}

api:
  encryption:
    key: "${api_key}"

ota:
- platform: esphome
  password: "${ota_pass}"

wifi:
  id: "${device_name}_wifi"
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "${recovery_pass}"

captive_portal:


# # # # # # # # # # # # # # # # # # # # # # #
# # # # #       ¡NO EDITAR!         # # # # #
# # # # # # # # # # # # # # # # # # # # # # #

# OBLIGATORIO: desactivar el log por UART
logger:
  baud_rate: 0

# Sección de configuración del dispositivo:
# - Interruptores
switch:
  # Pitido de confirmación de comandos, apagado por defecto
  - name: Pitido
    platform: template
    device_class: switch
    id: beep_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_beeper_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_beeper_state(false);
  
  # Indicador de temperatura en el frente de la unidad interior, encendido por defecto
  - name: Display
    platform: template
    device_class: switch
    id: display_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_display_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_display_state(false);
  
  # LEDs de actividad de datos en el módulo, apagados por defecto
  - name: LEDs del módulo
    platform: template
    device_class: switch
    id: ledflash_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_module_display_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_module_display_state(false);
          
  - name: Forzar configuración
    platform: template
    device_class: switch
    id: force_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_force_mode_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_force_mode_state(false);

# - Listas desplegables
select:
  # Configuración del barrido vertical
  - platform: template
    name: Barrido vertical
    id: vswing
    entity_category: config
    options:
      - "De arriba a abajo"
      - "En la mitad superior"
      - "En la mitad inferior"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          if (id(vswing).active_index() == 0){
            id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UP_DOWN);
          } else if (id(vswing).active_index() == 1){
            id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UPSIDE);
          } else if (id(vswing).active_index() == 2){
            id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::DOWNSIDE);
          }

  # Configuración de la posición fija del flap vertical
  - platform: template
    name: Posición flap vertical
    id: vfixing
    entity_category: config
    options:
      - "Última posición"
      - "Arriba del todo"
      - "Mitad superior"
      - "Centro"
      - "Mitad inferior"
      - "Abajo del todo"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          if (id(vfixing).active_index() == 0){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::LAST);
          } else if (id(vfixing).active_index() == 1){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_UP);
          } else if (id(vfixing).active_index() == 2){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::UP);
          } else if (id(vfixing).active_index() == 3){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::CENTER);
          } else if (id(vfixing).active_index() == 4){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::DOWN);
          } else if (id(vfixing).active_index() == 5){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_DOWN);
          }

climate:
  - platform: tclac
    name: "${device_name} Climate"
    id: ${device_name}climate
